# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: module_4/docs/conf.py

python:
  install:
    - requirements: module_4/requirements.txt
    # If your Sphinx autodoc imports your package, add one of these:
    # - method: pip
    #   path: module_4
    # (or use "." if you have a top-level package/pyproject)

formats:
  - htmlzip
  - pdf
