name: Tests
on:
  push:
    branches: [ main, master, redo_module4 ]
  pull_request:
    branches: [ main, master, redo_module4 ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Create Python package structure
      run: |
        touch module_4/src/__init__.py
        touch module_4/tests/__init__.py
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r module_4/requirements.txt
        
    - name: Run tests with coverage
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        PYTHONPATH: ${{ github.workspace }}/module_4
      working-directory: module_4
      run: |
        python -m pytest tests/ --cov=src --cov-report=term-missing --cov-fail-under=100 -m "web or buttons or analysis or db or integration"