name: Tests

on:
  push:
    branches: [ main, module3_optimization ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_gradcafe
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd module_4
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL
      run: |
        for i in {1..30}; do
          pg_isready -h localhost -p 5432 -U postgres && break
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Run tests with coverage
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_gradcafe
      run: |
        cd module_4
        pytest --cov=src --cov-report=term-missing --cov-fail-under=100

    - name: Generate coverage summary
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_gradcafe
      run: |
        cd module_4
        pytest --cov=src --cov-report=term-missing > coverage_summary.txt 2>&1 || true